######################################################################
# Automatically generated by qmake (2.01a) jeu. 5. juil. 11:29:34 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . \
              convexhull \
              geometrie \
              grammaire \
              gui \
              user \
              geometrie\objLoader \
              grammaire\condition \
              grammaire\parsing \
              grammaire\regles
INCLUDEPATH += .

# Input
HEADERS += convexhull/ConvexHull.h \
           convexhull/ConvexHullEPSWriter.h \
           convexhull/GrahamScanConvexHull.h \
           geometrie/FileReader.h \
           geometrie/Matrice2.h \
           geometrie/ObjReader.h \
           geometrie/Polygone.h \
           geometrie/Polygone_Detector.h \
           geometrie/Vec3.h \
           grammaire/MembreDroit.h \
           grammaire/MembreStandard.h \
           grammaire/Operateur.h \
           grammaire/OperateurCluster.h \
           grammaire/OperateurCycle.h \
           grammaire/OperateurEnsemble.h \
           grammaire/OperateurSequence.h \
           grammaire/Parser.h \
           grammaire/Regle.h \
           gui/MainWindow.h \
           gui/SimpleViewer.h \
           gui/treeitem.h \
           gui/treemodel.h \
           geometrie/objLoader/list.h \
           geometrie/objLoader/obj_parser.h \
           geometrie/objLoader/objLoader.h \
           geometrie/objLoader/string_extra.h \
           grammaire/condition/Condition.h \
           grammaire/condition/ConditionAdj.h \
           grammaire/condition/ConditionEgal.h \
           grammaire/condition/ConditionGenerale.h \
           grammaire/condition/ConditionUnique.h \
           grammaire/parsing/Noeud.h \
           grammaire/parsing/NonTerminal.h \
           grammaire/parsing/Terminal.h \
           grammaire/regles/CalculAttributs.h \
           user/parserescalier.cpp \
           user/ContrainteOrtho.cpp \
           user/ContrainteOrtho2.cpp \
           user/ContrainteAdjacenceExacte.cpp \
           user/parserHLM.cpp \
           user/ContrainteMurFenetre.cpp \
           user/ContrainteFenetreComplete.cpp \
           user/ContrainteClusterFenetre.cpp \
           user/CalculAttFenetreComplete.cpp
SOURCES += main.cpp \
           convexhull/ConvexHull.cpp \
           convexhull/ConvexHullEPSWriter.cpp \
           convexhull/GrahamScanConvexHull.cpp \
           convexhull/GSCHDemo.cpp \
           geometrie/FileReader.cpp \
           geometrie/Matrice2.cpp \
           geometrie/ObjReader.cpp \
           geometrie/Polygone.cpp \
           geometrie/Polygone_Detector.cpp \
           grammaire/MembreDroit.cpp \
           grammaire/MembreStandard.cpp \
           grammaire/Operateur.cpp \
           grammaire/OperateurCluster.cpp \
           grammaire/OperateurCycle.cpp \
           grammaire/OperateurEnsemble.cpp \
           grammaire/OperateurSequence.cpp \
           grammaire/Parser.cpp \
           grammaire/Regle.cpp \
           gui/MainWindow.cpp \
           gui/SimpleViewer.cpp \
           gui/treeitem.cpp \
           gui/treemodel.cpp \
           user/CalculAttFenetreComplete.cpp \
           user/ContrainteAdjacenceExacte.cpp \
           user/ContrainteClusterFenetre.cpp \
           user/ContrainteFenetreComplete.cpp \
           user/ContrainteMaison.cpp \
           user/ContrainteMurFenetre.cpp \
           user/ContrainteOrtho.cpp \
           user/ContrainteOrtho2.cpp \
           user/parserescalier.cpp \
           user/parserHLM.bgf.cpp \
           user/parserHLM.cpp \
           geometrie/objLoader/list.cpp \
           geometrie/objLoader/obj_parser.cpp \
           geometrie/objLoader/objLoader.cpp \
           geometrie/objLoader/objTester.cpp \
           geometrie/objLoader/string_extra.cpp \
           grammaire/condition/ConditionAdj.cpp \
           grammaire/condition/ConditionEgal.cpp \
           grammaire/condition/ConditionUnique.cpp \
           grammaire/parsing/Noeud.cpp \
           grammaire/parsing/NonTerminal.cpp \
           grammaire/parsing/Terminal.cpp

QT *= opengl xml svg	
LIBS *=-lQGLViewerd2
QMAKE_LIBDIR  += .
=======

QT *= opengl xml svg
LIBS *=-lQGLViewerd2
QMAKE_LIBDIR += .
>>>>>>> attributs
INCLUDEPATH += . ../QGLViewer/

QMAKE_CXXFLAGS+= -fpermissive
CXXFLAGS+= -fpermissive
<<<<<<< HEAD
CONFIG += console
=======
CONFIG += console
>>>>>>> attributs
